### ISSUE TITLE
Echo port in host links on vhost page?

### ISSUE THREAD

**Issue by defconjuan** [dockerizedrupal/vhost#13]
First off, thanks for your work on the dockerizedrupal container set. It's really solid.

I'm running several container sets, and each set has external ports bound to the apache, mysql, mailcatcher, phpmyadmin, and adminer containers so that I can access these outside of my docker host. 

Is there a way (say environment variable) to have the bound ports echoed in the links on the vhost overview page so that this page is useful off my docker host?

**Comment by viljaste** [comment]
Hey @defconjuan,

This is unfortunately not supported by vhost currently, but definitely will be supported in the future as it is quite useful feature.

I'll let you know when I have implemented this.

**Comment by viljaste** [comment]
Closing this as this project is unfortunately not active anymore.
